version: 2

project_name: whiskey

before:
  hooks:
    - go mod tidy

builds:
  - id: whiskey
    main: ./cmd/whiskey
    binary: whiskey

    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm64

    env:
      - CGO_ENABLED=0

    ldflags:
      - -s -w -X github.com/sxijyoti/whiskey/internal/cli.Version={{ .Version }}

archives:
  - id: default
    formats:
      - tar.gz

    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  github:
    owner: sxijyoti
    name: whiskey
