title = "Whiskey"
description = "Dependency-aware static site generator"

base_url = "https://whiskey-ssg.netlify.app"

theme = "terminal"

favicon = "images/logo.png"

[rss]
enabled = false
collections = [
    "blog"
]